name: Quicksand
version: 1.3.9.1
main: me.firebreath15.quicksand.main
commands:
  quicksand:
    description: QUICKSAND by Firebreath15!
    usage: /quicksand
    permission: quicksand.use
    permission-message: No Perm!
  qs:
    description: QUICKSAND by Firebreath15!
    usage: /qs
    permission: quicksand.use
    permission-message: No Perm!
permissions:
  quicksand.use:
    default: true
  quicksand.setspawn:
    default: op
  quicksand.setlobby:
    default: op
  quicksand.sign:
    default: op
  quicksand.join:
    default: false
  quicksand.setend:
    default: op
  quicksand.togglemax:
    default: op